scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instanceName: 'self'

  - job_name: node_exporter
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instanceName: 'self'

  - job_name: systemd_exporter
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9558']
        labels:
          instanceName: 'self'

  - job_name: docker_exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9200']
        labels:
          instanceName: 'self'

  - job_name: 'federation'
    scrape_interval: 1m
    scrape_timeout: 45s
    metrics_path: '/isids/prometheus'
    relabel_configs:
      # We use relabeling to dynamically add the instanceId param to the api url
      - source_labels: [instanceId]
        target_label: __metrics_path__
        replacement: '/isids/prometheus/${1}' # Use the instanceId as part of the metrics scrape url path
    params:
      'match[]':
        - '{__name__=~".+"}'
    http_sd_configs:
      - url: 'http://host.docker.internal:9823/isids/prometheus/targets'
        refresh_interval: 2m
